### PR TITLE
Handle surrogate pairs during scanning

### LINKED ISSUE #53: Emoji support
Current parser crashes when trying to load a yaml document with emojis in it.

```
    var emoji = "😃";
    String s = "YAML:  ${emoji} YAML Ain't Markup Language";
    var doc = loadYaml(s);
    print(doc['YAML']);
```

Error:

```
Error on line 1, column 8: Unexpected character.
  ╷
1 │ YAML:  😃 YAML Ain't Markup Language
  │        ^
  ╵

package:yaml/src/parser.dart 50:7    Parser.parse
package:yaml/src/loader.dart 165:37  Loader._loadMapping
package:yaml/src/loader.dart 86:16   Loader._loadNode
package:yaml/src/loader.dart 62:20   Loader._loadDocument
```

### PR DESCRIPTION
**Pull request by tamcy**
Fixes #53.

## The problem

Issue #53 is about adding support to Emoji characters, and the root cause of this issue is that the current YAML package doesn't handle surrogate pairs when parsing.

## Why?

In the [YAML spec](https://yaml.org/spec/1.2-old/spec.html#id2770814), a *character* is a Unicode code point (quote *Section 5.2: "All characters mentioned in this specification are Unicode code points. Each such code point is written as one or more bytes depending on the character encoding used. Note that in UTF-16, characters above #xFFFF are written as four bytes, using a surrogate pair."*). And in Section 5.1, the spec defines a list of acceptable Unicode *characters*, with UTF-16 surrogates explicitly excluded.

On the other hand, this package utilizes the `string_scanner` package to do string parsing or scanning, especially its `peekChar()` and `readChar()` methods. And the consumed "*character*" (in `int`) will be passed to the `_isStandardCharacter()` method in `scanner.dart` to test whether this Unicode *character* is an allowed one:

https://github.com/dart-lang/yaml/blob/e5984433a2803d5c67ed0abac5891a55040381ee/lib/src/scanner.dart#L1594-L1598

The problem is that a *character* (or char) returned by `peekChar()` or `readChar()` in `string_scanner` is actually a "code unit", and the "*character*" expected by `_isStandardCharacter()` is a "code point". As a result, `peekChar()` and `readChar()` can return a surrogate (usually the higher one) that represents a paired code units, and the value will be immediately rejected by `_isStandardCharacter()`.

The impact is that the package will reject all code points that requires a surrogate pairs if the string is not quoted. This doesn't only affect Emojis.

## A note on my previous attempt

I had submitted a pull request at https://github.com/dart-lang/string_scanner/pull/69, hoping that it can ease fixing the issue of the yaml package. But later I feel increasing uncomfortable about changing a codepoint-centric method to accept an `offset` argument that act upon code units. So I asked to make that pull request on hold, and decided to present my idea here for feedback first.

## What is in this pull request

This pull request doesn’t need any modifications to the `string_scanner` package as I’ve copied the required utility functions from it. Basically, I’ve implemented the following changes:

1. I have replaced all instances of `_scanner.readChar()` with `_scanner.readCodePoint()`. Although `_scanner.readChar()` could still be used in some areas, I’ve chosen to maintain consistency to prevent potential confusion or unintentional bugs in the future.
2. Instances that invoke `_isStandardCharacter()` have been modified to call the new method `_isStandardCharacterAt()`. This new method is responsible for checking and merging surrogate pairs, and then passing the actual codepoint/character to _isStandardCharacter().

## Misc.

benchmark.dart output before and after the fix (in JIT mode):

#### Before
```
Run #1: 0.124ms ============
Run #3: 0.116ms ===========
Run #4: 0.111ms ===========
Run #5: 0.110ms ===========
Run #8: 0.107ms ==========
Run #9: 0.106ms ==========
Run #10: 0.105ms ==========
Run #11: 0.099ms =========
Run #12: 0.092ms =========
Run #15: 0.091ms =========
Run #17: 0.089ms ========
Run #23: 0.077ms =======
Run #29: 0.065ms ======
Run #30: 0.064ms ======
Run #32: 0.059ms =====
Run #34: 0.057ms =====
Run #40: 0.056ms =====
Best   : 0.056ms =====
```

#### After
```
Run #1: 0.110ms ===========
Run #3: 0.100ms ==========
Run #5: 0.090ms =========
Run #9: 0.082ms ========
Run #10: 0.072ms =======
Run #11: 0.070ms =======
Run #12: 0.064ms ======
Run #14: 0.062ms ======
Run #18: 0.061ms ======
Run #21: 0.059ms =====
Best   : 0.059ms =====
```

### CODE REVIEW

**Comment by kevmoo** [comment]
@devoncarew ? @natebosch ?

**Comment by natebosch** [comment]
@lrhn - should we be using `package:characters` or does this look sufficient?

File: lib/src/scanner.dart [hunk 1]
```diff
@@ -787,7 +787,7 @@ class Scanner {
       while (_scanner.peekChar() == SP ||
           ((!_inBlockContext || !afterLineBreak) &&
               _scanner.peekChar() == TAB)) {
-        _scanner.readChar();
+        _scanner.readCodePoint();
```
Comment (lrhn) [inline lib/src/scanner.dart:790]: Should be able to use `readChar` here, since it's known to be either SP or TAB.

File: lib/src/scanner.dart [hunk 2]
```diff
@@ -822,7 +822,7 @@ class Scanner {
     var start = _scanner.state;
 
     // Eat '%'.
-    _scanner.readChar();
```
Comment (lrhn) [inline lib/src/scanner.dart:825]: Same. Known to be ASCII char.

File: lib/src/scanner.dart [hunk 3]
```diff
@@ -903,7 +903,7 @@ class Scanner {
   int _scanVersionDirectiveNumber() {
     var start = _scanner.position;
     while (_isDigit) {
-      _scanner.readChar();
+      _scanner.readCodePoint();
```
Comment (lrhn) [inline lib/src/scanner.dart:906]: Probably also safe to use `readChar`.

Several more below.

File: lib/src/scanner.dart [hunk 4]
```diff
@@ -1587,10 +1587,24 @@ class Scanner {
...
   }
 
+  bool _isStandardCharacterAt(int offset) {
+    var first = _scanner.peekChar(offset);
+    if (first == null) return false;
+
+    if (isHighSurrogate(first)) {
+      var next = _scanner.peekChar(offset + 1);
+      if (next != null && isLowSurrogate(next)) {
+        return _isStandardCharacter(decodeSurrogatePair(first, next));
```
Comment (lrhn) [inline lib/src/scanner.dart:1601]: There are no non-standard characters in the astral planes, so you can just return `true` here, without needing to decode.

It worries me a little to have a one-or-two code unit lookahead with a `bool` result, because returning `true` doesn't tell the reader how many code units it takes up. That means we're going to do the *same* surrogate pair matching again later. That seems wasteful. 
(Do we have any kind of performance measuring on this parser? It doesn't seem particularly efficient, with a pattern of first checking something to be valid, then parsing or consuming it, instead of doing it in one step.)

File: lib/src/scanner.dart [hunk 5]
```diff
@@ -1587,10 +1587,24 @@ class Scanner {
...
+      }
+    }
+
+    return _isStandardCharacter(first);
+  }
+
```
Comment (lrhn) [inline lib/src/scanner.dart:1607]: (Cannot unsee: The comment on `_asHex` below should say "hexadecimal", not "hexidecimal". Now I've said it. Feel free to ignore.)

File: lib/src/utils.dart [hunk 6]
```diff
@@ -43,3 +43,53 @@ YamlWarningCallback yamlWarningCallback = (message, [SourceSpan? span]) {
...
+/// A bit mask that covers the lower [_surrogateBits] of a code point, which can
+/// be used to extract the value of a surrogate or the low surrogate value of a
+/// code unit.
+const _surrogateValueMask = (1 << _surrogateBits) - 1;
+
+/// Returns whether [codePoint] is in the Unicode supplementary plane, and thus
+/// must be represented as a surrogate pair in UTF-16.
+bool inSupplementaryPlane(int codePoint) =>
+    codePoint >= _supplementaryPlaneLowerBound &&
+    codePoint <= _supplementaryPlaneUpperBound;
```
Comment (lrhn) [inline lib/src/utils.dart:78]: If the input is known to be a code point, then the `>=` should be sufficient.

This function does not seem to be used at all.

File: lib/src/utils.dart [hunk 7]
```diff
@@ -43,3 +43,53 @@ YamlWarningCallback yamlWarningCallback = (message, [SourceSpan? span]) {
...
+
+/// Returns whether [codeUnit] is a UTF-16 high surrogate.
+bool isHighSurrogate(int codeUnit) =>
+    (codeUnit & ~_surrogateValueMask) == _highSurrogateLowerBound;
```
Comment (lrhn) [inline lib/src/utils.dart:82]: Another option is:
```dart
 => codeUnit ^ _highSurrogateLowerBound < 0x400;
```

File: lib/src/utils.dart [hunk 8]
```diff
@@ -43,3 +43,53 @@ YamlWarningCallback yamlWarningCallback = (message, [SourceSpan? span]) {
...
+/// code unit.
+const _surrogateValueMask = (1 << _surrogateBits) - 1;
+
+/// Returns whether [codePoint] is in the Unicode supplementary plane, and thus
+/// must be represented as a surrogate pair in UTF-16.
+bool inSupplementaryPlane(int codePoint) =>
+    codePoint >= _supplementaryPlaneLowerBound &&
+    codePoint <= _supplementaryPlaneUpperBound;
+
+/// Returns whether [codeUnit] is a UTF-16 high surrogate.
```
Comment (lrhn) [inline lib/src/utils.dart:80]: Document predicates using a predicate phrase.
(Drop the "Returns", just start with "Whether". As a general rule, never ever start a DartDoc with the word "Returns".)

File: lib/src/utils.dart [hunk 9]
```diff
@@ -43,3 +43,53 @@ YamlWarningCallback yamlWarningCallback = (message, [SourceSpan? span]) {
...
+bool isHighSurrogate(int codeUnit) =>
+    (codeUnit & ~_surrogateValueMask) == _highSurrogateLowerBound;
+
+/// Returns whether [codeUnit] is a UTF-16 low surrogate.
+bool isLowSurrogate(int codeUnit) =>
+    (codeUnit >> _surrogateBits) == (_lowSurrogateLowerBound >> _surrogateBits);
```
Comment (lrhn) [inline lib/src/utils.dart:86]: That looks much more complicated than `isHighSurrogate`.
(It probably isn't *much* more complicated to compute since the second `>>` can be constant.)

Do either;
```dart
 => codeUnit ^ _lowSurrogateLowerBound < 0x400;
```
or 
```dart
 => (codeUnit & ~_surrogateValueMask) == _lowSurrogateLowerBound;
```

File: lib/src/utils.dart [hunk 10]
```diff
@@ -43,3 +43,53 @@ YamlWarningCallback yamlWarningCallback = (message, [SourceSpan? span]) {
   if (span != null) message = span.message(message);
   print(message);
 };
+
+// The following utility functions are copied from the string_scanner package.
```
Comment (lrhn) [inline lib/src/utils.dart:47]: Only copy what's needed. Some of these aren't used.

I think the following should be sufficient:
```dart
// The following utility functions are copied from the string_scanner package,
// and modified slightly.
//
// See https://en.wikipedia.org/wiki/UTF-16#Code_points_from_U+010000_to_U+10FFFF
// for documentation on how UTF-16 encoding works and definitions of various
// related terms.

/// The start of the UTF-16 high surrogate block.
const _highSurrogateLowerBound = 0xD800;

/// The start of the UTF-16 low surrogate block.
const _lowSurrogateLowerBound = 0xDC00;

/// Mask for the encoded bits of a surrogate value.
const _surrogateValueMask = 0x3FF;

/// Whether [codeUnit] is a UTF-16 high surrogate.
bool isHighSurrogate(int codeUnit) =>
    codeUnit ^ _highSurrogateLowerBound <= _surrogateValueMask;

/// Whether [codeUnit] is a UTF-16 low surrogate.
bool isLowSurrogate(int codeUnit) =>
    codeUnit ^ _lowSurrogateLowerBound <= _surrogateValueMask;
```

Copying something that we don't need just means more code to maintain, which we won't (I see no tests), and someone might one day start assuming that it works. Just keep it simple.

File: lib/src/utils.dart [hunk 11]
```diff
@@ -43,3 +43,53 @@ YamlWarningCallback yamlWarningCallback = (message, [SourceSpan? span]) {
...
+const _lowSurrogateLowerBound = 0xDC00;
+
+/// The number of low bits in each code unit of a surrogate pair that goes into
+/// determining which code point it encodes.
+const _surrogateBits = 10;
+
+/// A bit mask that covers the lower [_surrogateBits] of a code point, which can
+/// be used to extract the value of a surrogate or the low surrogate value of a
+/// code unit.
+const _surrogateValueMask = (1 << _surrogateBits) - 1;
```
Comment (lrhn) [inline lib/src/utils.dart:72]: Not much more readable than `0x3FF`. I'd just use the literal, and then not need `_surrogateBits` for anything.

**Review by lrhn — APPROVED** [review]
Generally, I'd change all the `.readCodePoint()`s that know they're reading ASCII characters back to just `.readChar()`. It should be more efficient. (If it isn't, we should make it more efficient,)

The only reason not to would be that you can't mix `readChar` and `readCodePoint` calls.
(If so, we should also fix that.)

File: lib/src/utils.dart (hunk 7 above)
Comment (tamcy) [reply lib/src/utils.dart:82]: If keeping the implementation with string_scanner is not needed, how about just use the implementation in [Flutter's TextPainter.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/text_painter.dart#L1269-L1285), i.e.

```dart
bool isHighSurrogate(int value) => value & 0xFC00 == 0xD800;
bool isLowSurrogate(int value) => value & 0xFC00 == 0xDC00;
```
?

File: lib/src/scanner.dart (hunk 4 above)
Comment (tamcy) [reply lib/src/scanner.dart:1601]: If we don't care about syncing the definition of "characters" with the yaml spec, the simplest solution would be foolow [another pull request](https://github.com/dart-lang/yaml/pull/125/commits/2532543315a10d39702bb559837aa90b10e5f6e6), i.e. just add the surrogate areas to the allowed list, maybe a little bit stricter to something like:

```dart
  bool _isStandardCharacter(int char) =>
      (char >= 0x020 && char <= 0x007E) ||
      (char >= 0x00A0 && char <= 0xD7FF) ||
      (char >= 0xE000 && char <= 0xFFFD) ||
      (char >= 0xD800 && char <= 0xDFFF) || // add this
      (char >= 0x10000 && char <= 0x10FFFF); // and remove this check as it will never be true
```

Then there will be no need to use `_scanner.readCodePoint();`. And the performance should just be the same.

Comment (natebosch) [reply lib/src/scanner.dart:1601]: @jonasfj - do you have an opinion on removing complexity by not fully following the yaml spec?

File: lib/src/utils.dart (hunk 7 above)
Comment (lrhn) [reply lib/src/utils.dart:82]: I was thinking the `0x400` would be a better immediate for fx ARM instructions, but it seems their immediates are not 12-bit, but 8-bit data + 4-bit shift, which all of 0x400, 0xFC00, 0xD800 and 0xDC00 fits in, so there should be no difference.

For compiling to Intel machine code, maybe this approoach would be better:
```dart
bool isHighSurrogate(int value) => value >> 10 == 0x36;
bool isLowSurrogate(int value) => value >> 10 == 0x37;
```
which can get implemented with one-byte immediates instead of a 32-bit ones (16-bit instructions are slow).
It should still just be two instructions on ARM.

(One can argue that this is worrying too much about small optimizations when we're not even sure the function will be inilined, and the real big saving would come from doing vector operations instead of checking individual characters. But I do worry about small stuff. :sunglasses:)

File: lib/src/scanner.dart (hunk 4 above)
Comment (lrhn) [reply lib/src/scanner.dart:1601]: Personally, I'm torn on that. No text should be containing unpaired surrogates, so 99.999% of the time, it makes not difference whether they're accepted, and it will just be faster. But I also like following specifications strictly!

We really should be parsing directly from UTF-8 if we can. Most of the time, input is a UTF-8 file, and decoding UTF-8 to UTF-16 first is just wasteful overhead, which *also* introduces the possibility of unpaired surrogates. Correctly decoded UTF-8 cannot contain unpaired surrogates (WTF-8 can, so we should just not accept that for YAML). 
We can then decode the slices that are string values and leave the rest as as-is (and not decode comments at all).

(Which is also another way to say that my attempts at minuscule optimizations are completely irrelevant if we are that inefficient from the very start.)

Comment (tamcy) [reply lib/src/scanner.dart:1601]: After reading your comment, I’m leaning more toward a simpler approach, i.e. just tweak `_isStandardCharacter()` and allow the UTF-16 surrogate range to pass through.
- Currently, the library also doesn’t check for invalid (unpaired) UTF-16 surrogates in quoted strings.
- Relaxing the check in `_isStandardCharacter()` may not improve but at least won’t break the expectation of standard compliance. In short it won't make things worse.
- Talking about expectation, I also think it is better for a library to behave the same when parsing quoted and unquoted string. While unlikely, just doing surrogate pair validation on unquoted string might introduce another report of unexpected behavior between the two type of strings.
- Less to no performance impact compared to this one.

@lrhn's suggestion sound valuable, but will take longer to implement (to me it sounds like a change from the ground up).

Anyway, if I want to submit a change towards `_isStandardCharacter()`, is it better to open a new pull request (#159 probably needs a rebase and add some test cases)? Or a force push this pull request is preferred? Thank you!

Comment (tamcy) [reply lib/src/scanner.dart:1601]: Oops, looks like what I said above was wrong: The Yaml spec says:
> To ensure [JSON compatibility](https://yaml.org/spec/1.2.2/#yaml-directives), YAML [processors](https://yaml.org/spec/1.2.2/#processes-and-models) must allow all non-C0 characters inside [quoted scalars](https://yaml.org/spec/1.2.2/#double-quoted-style). To ensure readability, non-printable characters should be [escaped](https://yaml.org/spec/1.2.2/#escaped-characters) on output, even inside such [scalars](https://yaml.org/spec/1.2.2/#scalars).

So quoted and unquoted scalers are not analogous in this context. Sorry for the noise!

File: lib/src/scanner.dart (hunk 5 above)
Comment (tamcy) [reply lib/src/scanner.dart:1607]: Found 3 occurrences, I'll ignore them in this PR.

**Comment by tamcy** [comment]
In the latest revision I changed back to use `readChar()` whenever possible. Also I have remove the need to decode the surrogate for further checking, because a valid surrogate pair itself should be of the range of `0x10000` to `0x10FFFF`, so just checking validity of the high and low surrogate is enough.

**Comment by kevmoo** [comment]
Any interest in moving this forward?

**Comment by kevmoo** [comment]
Thanks so much, @tamcy !
